bootdo:
  uploadPath: /var/uploaded_files/
logging:
  level:
    root: info
    com.bootdo: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.251.90:3306/scenic?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    initialSize: 5
    minIdle: 3
    maxActive: 10
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

##用户默认密码
user:
  defaultpassword: Passwd!23

system:
  secritmap: "[{restcode:8,secrit:rt,sourcesystem:0}]"


## 定时任务配置
task:
  ##30秒执行一次
  ping: 0/30 * * * * ?
  ##检查资产外出超过天数(每天23点执行一次)
  checkOutDay: 0 0 23 * * ?
  ##向每个连接的RFID发送读取请求
  rfidsend: 0/30 * * * * ?
  ##分析数据库中读到的RFID记录
  analysisrfid: 0/30 * * * * ?

## mail
mail:
  #邮件服务器的SMTP地址
  host: mrl.azell.com
  #邮件服务器的SMTP端口，可选，默认25
  port: 25
  #发件人
  from: fafcumsq@ford.com
  #用户名，默认为发件人邮箱前缀
  user: FAFCUMSQ

##手机号校验
phoneregex: ^[1][3,4,5,6,7,8,9][0-9]{9}$